### ISSUE TITLE
Problems with touchkit 4.1 with firefox. #435

### ISSUE THREAD

**Issue by tullio0106** [vaadin/touchkit#439] opened 2021-07-16 15:30 UTC
The #435 was closed but the problem is not yet solved.
Could You reopen #435 or continue on this issue ?
Tks
Tullio

**Comment by TatuLund** [comment] 2021-07-26 13:31
The Firefox issue will be fixed by https://github.com/vaadin/touchkit/pull/440

**Comment by tullio0106** [comment] 2021-07-26 14:09
Please what's the new version number in order to download it using maven ?

**Comment by TatuLund** [comment] 2021-07-27 09:47
The fix of the Firefox issue is included in version 4.2.2 released yesterday.

**Closed as completed by TatuLund** 2021-07-27 09:47 UTC
Labels: bug, BFP

**Comment by tullio0106** [comment] 2021-07-27 13:03
Unfortunately the situation is even wrost.

Now in every situation I get an error :

java.lang.NullPointerException

    at com.vaadin.addon.touchkit.settings.TouchKitSettings$2.handleRequest(TouchKitSettings.java:308)

    at com.vaadin.server.communication.SessionRequestHandler.handleRequest(SessionRequestHandler.java:63)

    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1438)

    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:380)

    at com.vaadin.addon.touchkit.server.TouchKitServlet.service(TouchKitServlet.java:63)

    at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)

    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)

    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)

    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

    at axioma.web.crm.ui.filter.CrmApplicationFilter.doFilter(CrmApplicationFilter.java:63)

    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)

    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)

    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)

    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)

    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)

    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)

    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)

    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)

    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)

    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)

    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)

    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1579)

    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)

    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)

    at java.lang.Thread.run(Thread.java:748)

Did I miss something ?

**Comment by TatuLund** [comment] 2021-07-27 14:14
@tullio0106 This NPE is not related to previous Chrome and Firefox issues. The exception is thrown because request.getPathInfo() returned null. This sounds odd to me and requires further investigation. New ticket is needed about this and more info how to reproduce. The code where exception is however part of the new implementation for PWA, i.e. getPathInfo() is used to lookup the manfifest file of the PWA.

**Comment by TatuLund** [comment] 2021-07-27 14:49
Actually there was the same bug in Touchkit 5, and it was fixed there https://github.com/parttio/touchkit/commit/d7b07dbd774b45599e7af7143d8b128ad144ac00

I will cherry pick the fix. For some reason I did not see this NPE in parking demo app.

**Comment by TatuLund** [comment] 2021-07-27 15:00
I uploaded new version 4.2.3 to directly. Could you try that again.

**Comment by tullio0106** [comment] 2021-07-28 08:51
It seems to work correctly.

Tks for Your help.

Tullio
